// src/components/BrowserNotSupported/BrowserNotSupported.svelte
<script lang="ts">
  import chromeIcon from '../../assets/chrome.svg';
</script>

<div class="unsupported">
  <h2>This browser is not yet supported</h2>
  <p>This app requires APIs currently only supported in Chrome.</p>
  <a href="https://www.google.com/chrome/" target="_blank">
    <img src={chromeIcon} alt="Chrome" width="24" />
    Google Chrome
  </a>
</div>

<style>
.unsupported {
  text-align: center;
  padding: 1rem;
}
.unsupported a {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  margin-top: 0.5rem;
}
</style>

// src/components/BrowserNotSupported/BrowserNotSupported.tsx
import Link from '@mui/material/Link';
import Typography from '@mui/material/Typography';

import chromeIcon from 'assets/chrome.svg';

import styles from './BrowserNotSupported.module.css';

const BrowserNotSupported = () => {
  return (
    <div className={styles.root}>
      <Typography variant="h6">This browser is not yet supported</Typography>
      <Typography variant="subtitle1">
        This app requires the following browser APIs which are currently only
        supported in Chrome:
      </Typography>
      <Typography variant="body2" color="text.secondary">
        • Document Picture-in-Picture API
        <br />
        • MediaStreamTrack Processor API
        <br />• MediaStreamTrack Generator API
      </Typography>
      <Link
        className={styles.chromeLink}
        href="https://www.google.com/chrome/"
        target="_blank"
        color="secondary"
        underline="none"
      >
        <img className={styles.chromeIcon} src={chromeIcon} />
        Google Chrome
      </Link>
    </div>
  );
};

export default BrowserNotSupported;
