// src/components/TeleprompterSelect/TeleprompterSelect.svelte
<script lang="ts">
import DeviceSelect from '../DeviceSelect/DeviceSelect.svelte';
import { isTeleprompterOpen } from '../../stores/ui';
import TeleprompterIcon from '../ShapeSelect/icons/TeleprompterIcon.svelte';
$: teleValue = $isTeleprompterOpen ? 'show' : 'hide';
function change(v: string) {
  isTeleprompterOpen.set(v === 'show');
}
</script>

<DeviceSelect
  label="Teleprompter"
  options={[{ value: 'hide', label: 'Hide' }, { value: 'show', label: 'Show' }]}
  bind:value={teleValue}
  onChange={change}
>
  <TeleprompterIcon />
</DeviceSelect>

// src/components/TeleprompterSelect/TeleprompterSelect.tsx
import MenuItem from '@mui/material/MenuItem';
import DeviceSelect from 'components/DeviceSelect';
import { TeleprompterIcon } from 'components/ShapeSelect/icons/TeleprompterIcon';
import { useState } from 'react';
import Teleprompter from 'components/Teleprompter';

const TeleprompterSelect = () => {
  const [showTeleprompter, setShowTeleprompter] = useState(false);

  return (
    <>
      <DeviceSelect
        startAdornment={
          <div onClick={() => setShowTeleprompter(!showTeleprompter)} style={{ cursor: 'pointer' }}>
            <TeleprompterIcon />
          </div>
        }
        value={showTeleprompter ? 'show' : 'hide'}
        onChange={(event) => setShowTeleprompter(event.target.value === 'show')}
      >
        <MenuItem value="hide">Hide Teleprompter</MenuItem>
        <MenuItem value="show">Show Teleprompter</MenuItem>
      </DeviceSelect>
      {showTeleprompter && <Teleprompter />}
    </>
  );
};

export default TeleprompterSelect;
